name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'  # Tu versión de Java

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test

