name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.4

    - name: Set up JDK
      uses: actions/setup-java@v2.5.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package

    - name: Run tests
      run: mvn test
